name:               "Timo Milbich"
description:        "Ph.D. Student - Computer Vision Heidelberg University"

url:                ""
author:             "timomilbich"
twitter:            "timoMil"
email:              "timo_milbich@gmx.de"
github:             "timomilbich"
#pinterest:          "jhondoe"
linkedin:           "timomilbich"

disqus_shortname:   "timomilbich"

background:         "/files/bg_crop.jpeg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "News"
    href:           "/"
  - name:           "About Me"
    href:           "/aboutme"
  - name:           "Education"
    href:           "/career"
  - name:           "Publications"
    href:           "/publications"
  - name:           "Contact"
    href:           "/contact"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
